name: Android Tests

on:
  push:
    branches: [ "main", "capacitor" ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ "main", "capacitor" ]
    paths:
      - 'android/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Android Test Container
      run: docker build -t versicle-android -f Dockerfile.android .

    - name: Run Android Tests
      run: docker run --rm versicle-android
